title: Security Wonks
description: >-
  A collective of security professionals dedicated to advancing the field 
  through research, discourse, and community.
baseurl: ""
url: "https://secwonks.org"

# Author
author: Warren Raquel
  name: Security Wonks

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Permalink style for blog
permalink: /blog/:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - categories
